apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: "terraform-20260727144949219300000001.c3ss2ksmue10.eu-north-1.rds.amazonaws.com"
  DB_NAME: "taskdb"
  DB_PORT: "5432"
  DB_USER: "postgres"
  PORT: "3000"
